credentials:
  api_key: 
  project_id: 

outputs:
  model_outfile: sorghum/object_detection_model.pth
  plot_outfile: sorghum/object_detection_loss.png
  train_outdir: sorghum/train
  test_outdir: sorghum/test
  validation_outdir: sorghum/validation
  download_from_labelbox: true

training_parameters:
  train_model: True
  verbose: True
  classes: [panicle]
  shuffle: False
  batch_size: 4
  epochs: 10
  learning_rate: 0.001
