credentials:
  api_key: <your LabelBox API key here>
  project_id: <your LabelBox project ID here>

outputs:
  model_outfile: lettuce/object_detection_model.pth
  plot_outfile: lettuce/object_detection_loss.png
  train_outdir: lettuce/train
  test_outdir: lettuce/test
  validation_outdir: lettuce/validation

training_parameters:
  train_model: True
  verbose: True
  classes: [plant]
  shuffle: False
  batch_size: 4
  epochs: 10
  learning_rate: 0.001
